---
title: "Regression Analysis Methodologies for Continous Response Variables"
author: "Wendy Frankel"
date: "2026-01-14"
categories: [how-to, code, analysis]
---

------------------------------------------------------------------------

Regression analysis is an evolving, useful, and important tool within the data science toolbox. Various methods are commonly used within scientific papers and industry. Therefore, understanding the different kinds of regression analysis, and being able to use them for the right purposes, is very important. However, there are so many kinds of regression analysis that it can be difficult to keep them all straight, and understand when they may be used. In this bloc post, I'll be going over some of the most important kinds of regression analysis, when dealing with a continuous response variable.

1.  **Local Conditioned Quantile**

Non-parametric quantile regression models how different quantiles (e.g., the median or upper tail) of a response variable depend on predictors **without assuming a specific functional form** for that relationship. Instead of estimating the conditional mean, it directly estimates conditional quantiles using flexible methods such as kernel smoothing, splines, or local polynomial fitting. This makes it especially useful for capturing nonlinear effects and heteroskedasticity, and for understanding how covariates influence the entire distribution of the response rather than just its average.

Lipsitz et al., 2018 outlines a package called quantreg.nonpar, which can implement nonparametric quantile regression in the following way:

```{r}
library(quantreg.nonpar)

#fitting the model
fit <- npqr(y ~ x, tau = 0.5, data = mydata)
summary(fit)

#making predictions
newx <- data.frame(x = seq(min(mydata$x), max(mydata$x), length.out = 100))
pred <- predict(fit, newdata = newx)
```

Copyright © G. Alexi Rodríguez-Arelis, Payman Nickchi, Rodolfo Lourenzutti, and Vincenzo Coia. <https://creativecommons.org/licenses/by/4.0/>

Lipsitz, M., Belloni, A., Chernozhukov, V., & Fernández-Val, I. (2016). *quantreg.nonpar: An R package for performing nonparametric series quantile regression*. arXiv. <https://arxiv.org/abs/1610.08329>
